---
title: "Task_3"
author: watsoncl 
output: 
  html_document:
    keep_md: true
    theme: flatly
    toc: true
    toc_float: true
    code_folding: hide
---

##Background

You have just been hired to a new data science team, and you need to collaborate on projects. The team lead told you to connect to your git repository on Github and edit the README.md in your repository. She wants you to describe who you are in a short paragraph.

##Reading

This reading will help you complete the tasks below.

o [Chapter 4: Happy Git and Github for the useR - Installation](http://happygitwithr.com/installation-pain.html)

o [Chapter 5: Happy Git and Github for the useR - GitHub](http://happygitwithr.com/github-acct.html)

o [Chapter 7: Happy Git and Github for the useR - Install Git](http://happygitwithr.com/install-git.html)

o [Chapter 8: Happy Git and Github for the useR - Using Git](http://happygitwithr.com/hello-git.html)

o [Using the R-Studio GUI by R-Studio](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)

o [Chapter 8: R for Data Science - Projects](http://r4ds.had.co.nz/workflow-projects.html)

o [MCS 335, Git, and Github use](https://byuistats.github.io/M335/git_335.html)

o [R-Studio and the Git GUI](https://www.youtube.com/watch?v=E2d91v1Twcc)

##Tasks

[x] Install git on your computer

[x] Make sure your GitHub account is registered

[x] Work through readings on git and github

[x] Make sure git works in R-Studio

[x] Update your README.md in your repository (you will need to give me time to create your repo after you post your username) 

[x] Type one or two sentences that describe you

[x] Make sure you pull and push

[x] Check your folder structure in your git repo to match the format for our class - see MCS 335 Folder Structure

##Additional Links

o Chapter 10: Happy Git and Github for the useR - Version Control

o git

o githug

o Git for R users

o Getting Ready

o Intro Tutorial

o Advanced Tutorial




