---
title: "Task_120"
author: watsoncl 
output: 
  html_document:
    keep_md: true
    theme: flatly
    toc: true
    toc_float: true
    code_folding: hide
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(USAboundaries)
library(sf)
library(maps)
library(ggrepel)
library(tidyverse)
library(ggplot2)
library(maptools)
```

##Background

We have been asked by the state of Idaho to visualize permitted well locations with a production of more than 5000 gallons and the spatial relationship of the large wells to the locations of large dams (surface area larger than 50 acres). They have provided a a shp file for us and given us a web address for the well, dam, and water locations. They would like to have the Snake River and Henrys Fork rivers plotted.
Their US map is projected to show the entire US. You will need to subset the data to Idaho and then reproject the map, so Idaho is not tilted.

##Reading

This reading will help you complete the tasks below.

o [Using library(sf) to read in spatial data](https://r-spatial.github.io/sf/articles/sf2.html)

o [Josh Wills on big data (tech data scientist)](https://www.youtube.com/watch?v=Ewd5PXgLXlU&feature=youtu.be)

o [Issues with Spatial Aggregation](https://www.youtube.com/watch?v=wn5larsRHro)

##Tasks
[ ] Watch the Josh Wills video on big data and be prepared for a disucssion in class.
[ ] Read in all four of the necessary shp file datasets (see description)
[ ] Filter all the data for the specific needs of Idaho
[ ] Create a .png image that plots the required information
[ ] Save your script and .png files to GitHub
[ ] Be prepared to discuss your observations of the well and dam locations in our next class meeting







































